# Generated by Django 4.0.3 on 2022-04-07 11:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question', models.CharField(blank=True, max_length=256, null=True)),
                ('option1', models.CharField(blank=True, max_length=256, null=True)),
                ('option2', models.CharField(blank=True, max_length=256, null=True)),
                ('option3', models.CharField(blank=True, max_length=256, null=True)),
                ('option4', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subject_name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=32)),
                ('questions', models.ManyToManyField(blank=True, to='meta_app.question')),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'UserTypes',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='meta_app.usertype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='TestExecuted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.userprofile')),
            ],
            options={
                'db_table': 'TakenTests',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(blank=True, default=0, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.userprofile')),
                ('students', models.ManyToManyField(blank=True, null=True, to='meta_app.student')),
                ('subjects', models.ManyToManyField(blank=True, null=True, to='meta_app.subject')),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='StudentTeacherLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('record_url', models.URLField(blank=True, null=True)),
                ('lesson_date', models.DateField()),
                ('lesson_material', models.URLField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.teacher')),
            ],
            options={
                'db_table': 'Lessons',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.userprofile'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='meta_app.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='meta_app.teacher'),
        ),
    ]
