# Generated by Django 4.0.3 on 2022-04-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
