# Generated by Django 4.0.3 on 2022-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0002_remove_student_subjects_remove_student_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='meta_app.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='meta_app.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='meta_app.student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='meta_app.subject'),
        ),
    ]
