# Generated by Django 4.0.3 on 2022-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0003_student_subjects_student_teachers_teacher_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteacherlesson',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
