# Generated by Django 4.0.3 on 2022-04-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0004_studentteacherlesson'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentteacherlesson',
            table='Lessons',
        ),
    ]
