# Generated by Django 4.0.3 on 2022-04-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0004_studentteacherlesson_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecuted',
            name='user',
        ),
        migrations.AddField(
            model_name='testexecuted',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='meta_app.student'),
            preserve_default=False,
        ),
    ]
