# Generated by Django 4.0.3 on 2022-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0005_remove_testexecuted_user_testexecuted_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteacherlesson',
            name='student_full_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentteacherlesson',
            name='teacher_full_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
