# Generated by Django 4.0.3 on 2022-04-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0005_alter_studentteacherlesson_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertype',
            table='UserTypes',
        ),
    ]
