# Generated by Django 4.0.3 on 2022-04-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0007_studentteacherlesson_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentteacherlesson',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
