# Generated by Django 4.0.3 on 2022-04-06 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0008_userprofile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('question', models.CharField(blank=True, max_length=256, null=True)),
                ('option1', models.CharField(blank=True, max_length=256, null=True)),
                ('option2', models.CharField(blank=True, max_length=256, null=True)),
                ('option3', models.CharField(blank=True, max_length=256, null=True)),
                ('option4', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=32)),
                ('questions', models.ManyToManyField(blank=True, to='meta_app.question')),
            ],
            options={
                'db_table': 'Test',
            },
        ),
        migrations.CreateModel(
            name='TestExecuted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meta_app.userprofile')),
            ],
            options={
                'db_table': 'TakenTests',
            },
        ),
    ]
