# Generated by Django 4.0.3 on 2022-04-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0009_question_test_testexecuted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.RESTRICT, to='meta_app.usertype'),
        ),
    ]
